language: node_js
os:
    - linux
    - windows
node_js:
    - "stable"
    - "6.9.1"
    - "4.6.1"
sudo: false
before_script:
  - npm install -g gulp
script: gulp
script:
    - npm test
services:
  - mongodb
after_success:
  - bash <(curl -s https://codecov.io/bash)
